#________     __________________                         .__   
#\______ \   /  _____/\______   \_____     ____    ____  |  |  
# |    |  \ /   \  ___ |     ___/\__  \   /    \ _/ __ \ |  |  
# |    `   \\    \_\  \|    |     / __ \_|   |  \\  ___/ |  |__
#/_______  / \______  /|____|    (____  /|___|  / \___  >|____/
#        \/         \/                \/      \/      \/         v2.0

panel:
 listen: '0.0.0.0'
 port: 8443
 cert: wss.pem
 admin_token: 
 max_show: 10
dungeon:
 maxtime: 20
 a:
  place: 
  maxstrenth: 10
  minstrenth: 0
 b:
  place: 
  maxstrenth: 20
  minstrenth: 1